robots:

  - name: "red_standard_robot1"
    color: "red"
    x_pose: "4.3"
    y_pose: "3.35"
    z_pose: "1.2"
    yaw: "0.0"

  - name: "blue_standard_robot1"
    color: "blue"
    x_pose: "10.0"
    y_pose: "4.5"
    z_pose: "1.2"
    yaw: "3.14"